// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/p/[poll].tsx";
import * as $2 from "./routes/p/[poll]/[vote].tsx";
import * as $3 from "./routes/p/[poll]/results.ts";
import * as $4 from "./routes/status.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/p/[poll].tsx": $1,
    "./routes/p/[poll]/[vote].tsx": $2,
    "./routes/p/[poll]/results.ts": $3,
    "./routes/status.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
